### PR TITLE
Wrap memory allocation functions to abort on failure

### LINKED ISSUE #112: Should use memory allocation routines that crash on failure, or properly handle allocation failures
When running cppcheck, Ubuntu Security Team noticed a memory leak if realloc() fails:

```
src/input.c:231:29: error: Common realloc mistake: 'array' nulled but not freed upon failure [memleakOnRealloc]
                            array = (struct wpe_input_xkb_keymap_entry*)realloc(array, array_allocated_size * sizeof(struct wpe_input_xkb_keymap_entry));
```

"If realloc fails, the array pointer will become NULL and the old allocation will be lost (memory leak)." Nowadays this code lives in input-xbc.c, line 234.

Problem is, it's not just here. Other code in libwpe is not prepared for calloc() to fail. It's probably best to switch to memory allocation routines that crash if they fail so you don't have to check every single allocation for failure. I notice libwpe does not depend on GLib, but safer GLib equivalents would be `g_realloc()` or `g_new0()`. Easy enough to write your own wrapper, though.

(Interestingly, I checked wpebackend-fdo and it does not appear to have the same issue.)

### PR DESCRIPTION
**Pull request by aperezdc**
Be consistent in handling memory allocation failures by always aborting execution. Previously, some call sites for `malloc`/`calloc`/`realloc` tried to handle allocation failures, but some others did not. Given that WebKit's FastMalloc will itself abort on allocation failures, doing the same in libwpe keeps behaviour consistent.

A new `alloc-private.h` header redefines the libc functions with `wpe_` prefixes, which perform checks after invoking the libc versions, and use a common `wpe_alloc_fail()`. The actual implementation is done through macros in order to pass along `__FILE__`/`__LINE__` to a set of inline functions defined directly in the header, in order to help out debug failures. As a bonus, GCC's `poison` pragma (supported by Clang, too) prevents accidental usage of the libc allocation functions.

As a side effect, simplify the call sites which attempted to handle failures, which now can assume that allocations never fail.

----

Fixes #112

### CODE REVIEW

File: src/alloc-private.h [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+#define WPE_USERESULT __attribute__((warn_unused_result))
+#else
+#define WPE_USERESULT
+#endif /* __has_attribute(warn_unused_result) */
+
+#ifdef __cplusplus
+extern "C"
+#endif /* __cplusplus */
+    WPE_NORETURN void
+    wpe_alloc_fail(const char* file, unsigned line, size_t amount);
```
Comment (mcatanzaro) [inline src/alloc-private.h:60]: Looks like indentation is messed up here.

File: src/alloc.c [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+#include "alloc-private.h"
+
+#include <stdio.h>
+
+void
+wpe_alloc_fail(const char* file, unsigned line, size_t amount)
+{
+    fprintf(stderr, "%s:%u: failed to allocate %zu bytes\n", file, line, amount);
+    fflush(stderr);
```
[the remark this answers is not in the document]
Comment (aperezdc) [reply src/alloc.c:35]: Unless the application has called `setvbuf()` (or some variant), in which case IMO it's better to play it safe as this is library code. It's not rare that running under process supervision (systemd/daemontools/etc.) the logged standard streams may be buffered.

File: src/alloc-private.h (hunk 1 above)
Comment (aperezdc) [reply src/alloc-private.h:60]: I'm fine with it, this is what `clang-format` suggested with our current settings, and I kind of like it that the oddball indentation in this case actually makes it clearer that the `extern "C"` applies only to this function declaration 😉

Comment (mcatanzaro) [reply src/alloc-private.h:60]: Might be worth copy/pasting `G_BEGIN_DECLS` and `G_END_DECLS` and replacing the `G_` with `WPE_`.

Comment (clopez) [inline src/alloc-private.h:60]: nitpick: the indentation on this two lines seems wrong, isn't it? Also maybe add a new line after the #endif

Comment (aperezdc) [reply src/alloc-private.h:60]: We have a `.clang-format` configuration, and a CI job to use for style checks—which passed. If you believe this is wrong, please open a PR suggesting changes to the `.clang-format` file.

File: src/alloc-private.h [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+#define wpe_calloc(nmemb, size) wpe_calloc_impl((nmemb), (size), __FILE__, __LINE__)
+#define wpe_realloc(p, size)    wpe_realloc_impl((p), (size), __FILE__, __LINE__)
+#define wpe_malloc(size)        wpe_malloc_impl((size), __FILE__, __LINE__)
+#define wpe_free                free
+
+/* Prevent usage of unwrapped functions from this point onwards. */
+#pragma GCC poison malloc
+#pragma GCC poison realloc
+#pragma GCC poison calloc
+#pragma GCC poison free
```
Comment (clopez) [inline src/alloc-private.h:103]: This can be wrote in a single line:
```
#pragma GCC poison malloc realloc calloc free
```

Comment (aperezdc) [reply src/alloc-private.h:103]: This is nice to know, but I think it's not worth it to amend the patch that has already landed. If usage of this pragma pops out again, I'll keep it in mind, thanks!
